### ISSUE TITLE
learnable label-smoothing

### ISSUE THREAD

**Issue by Rotem-BZ** [ondrejbohdal/meta-calibration#1]
Hey, is the learnable label smoothing presented in the paper (not regularization) available in this implementation?

**Comment by ondrejbohdal** [comment]
Hello, the implementation currently only includes the approach (regularization) used in the earlier version of the paper. I'll be happy to add learnable label smoothing if wanted.

**Comment by Rotem-BZ** [comment]
That would be great!

**Comment by ondrejbohdal** [comment]
Sure, I'll try to do that some time next week after the current conference deadline.

**Comment by ondrejbohdal** [comment]
I've just added the implementation of learnable label smoothing.
